#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v18
# autospec commit: eaa4f711da30
#
Name     : createrepo_c
Version  : 1.1.3
Release  : 86
URL      : https://github.com/rpm-software-management/createrepo_c/archive/1.1.3/createrepo_c-1.1.3.tar.gz
Source0  : https://github.com/rpm-software-management/createrepo_c/archive/1.1.3/createrepo_c-1.1.3.tar.gz
Summary  : Creates a common metadata repository
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: createrepo_c-bin = %{version}-%{release}
Requires: createrepo_c-data = %{version}-%{release}
Requires: createrepo_c-lib = %{version}-%{release}
Requires: createrepo_c-license = %{version}-%{release}
Requires: createrepo_c-man = %{version}-%{release}
Requires: createrepo_c-python = %{version}-%{release}
Requires: createrepo_c-python3 = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : bzip2-dev
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : file-dev
BuildRequires : libxml2-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(bash-completion)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(libzstd)
BuildRequires : pkgconfig(modulemd-2.0)
BuildRequires : pkgconfig(rpm)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : popt-dev
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : rpm-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Log-URL-on-failure.patch
Patch2: 0002-Add-a-user-agent.patch

%description
C implementation of Createrepo.
A set of utilities (createrepo_c, mergerepo_c, modifyrepo_c)
for generating a common metadata repository from a directory of
rpm packages and maintaining it.

%package bin
Summary: bin components for the createrepo_c package.
Group: Binaries
Requires: createrepo_c-data = %{version}-%{release}
Requires: createrepo_c-license = %{version}-%{release}

%description bin
bin components for the createrepo_c package.


%package data
Summary: data components for the createrepo_c package.
Group: Data

%description data
data components for the createrepo_c package.


%package dev
Summary: dev components for the createrepo_c package.
Group: Development
Requires: createrepo_c-lib = %{version}-%{release}
Requires: createrepo_c-bin = %{version}-%{release}
Requires: createrepo_c-data = %{version}-%{release}
Provides: createrepo_c-devel = %{version}-%{release}
Requires: createrepo_c = %{version}-%{release}

%description dev
dev components for the createrepo_c package.


%package lib
Summary: lib components for the createrepo_c package.
Group: Libraries
Requires: createrepo_c-data = %{version}-%{release}
Requires: createrepo_c-license = %{version}-%{release}

%description lib
lib components for the createrepo_c package.


%package license
Summary: license components for the createrepo_c package.
Group: Default

%description license
license components for the createrepo_c package.


%package man
Summary: man components for the createrepo_c package.
Group: Default

%description man
man components for the createrepo_c package.


%package python
Summary: python components for the createrepo_c package.
Group: Default
Requires: createrepo_c-python3 = %{version}-%{release}

%description python
python components for the createrepo_c package.


%package python3
Summary: python3 components for the createrepo_c package.
Group: Default
Requires: python3-core

%description python3
python3 components for the createrepo_c package.


%prep
%setup -q -n createrepo_c-1.1.3
cd %{_builddir}/createrepo_c-1.1.3
%patch -P 1 -p1
%patch -P 2 -p1
pushd ..
cp -a createrepo_c-1.1.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1722975604
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DCMAKE_CTEST_ARGUMENTS="--verbose --output-on-failure" \
-DLIB_INSTALL_DIR=/usr/lib64 \
-DWITH_ZCHUNK=OFF \
-DENABLE_DRPM=OFF \
-DWITH_LIBMODULEMD=ON  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DCMAKE_CTEST_ARGUMENTS="--verbose --output-on-failure" \
-DLIB_INSTALL_DIR=/usr/lib64 \
-DWITH_ZCHUNK=OFF \
-DENABLE_DRPM=OFF \
-DWITH_LIBMODULEMD=ON  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd clr-build
make tests
ctest --output-on-failure
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1722975604
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/createrepo_c
cp %{_builddir}/createrepo_c-%{version}/COPYING %{buildroot}/usr/share/package-licenses/createrepo_c/4cc77b90af91e615a64ae04893fdffa7939db84c || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/createrepo_c
/V3/usr/bin/mergerepo_c
/V3/usr/bin/modifyrepo_c
/V3/usr/bin/sqliterepo_c
/usr/bin/createrepo_c
/usr/bin/mergerepo_c
/usr/bin/modifyrepo_c
/usr/bin/sqliterepo_c

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/createrepo_c
/usr/share/bash-completion/completions/mergerepo_c
/usr/share/bash-completion/completions/modifyrepo_c
/usr/share/bash-completion/completions/sqliterepo_c

%files dev
%defattr(-,root,root,-)
/usr/include/createrepo_c/checksum.h
/usr/include/createrepo_c/compression_wrapper.h
/usr/include/createrepo_c/constants.h
/usr/include/createrepo_c/createrepo_c.h
/usr/include/createrepo_c/createrepo_shared.h
/usr/include/createrepo_c/deltarpms.h
/usr/include/createrepo_c/error.h
/usr/include/createrepo_c/helpers.h
/usr/include/createrepo_c/koji.h
/usr/include/createrepo_c/load_metadata.h
/usr/include/createrepo_c/locate_metadata.h
/usr/include/createrepo_c/mergerepo_c.h
/usr/include/createrepo_c/misc.h
/usr/include/createrepo_c/modifyrepo_shared.h
/usr/include/createrepo_c/package.h
/usr/include/createrepo_c/parsehdr.h
/usr/include/createrepo_c/parsepkg.h
/usr/include/createrepo_c/repomd.h
/usr/include/createrepo_c/sqlite.h
/usr/include/createrepo_c/threads.h
/usr/include/createrepo_c/updateinfo.h
/usr/include/createrepo_c/version.h
/usr/include/createrepo_c/xml_dump.h
/usr/include/createrepo_c/xml_file.h
/usr/include/createrepo_c/xml_parser.h
/usr/lib64/libcreaterepo_c.so
/usr/lib64/pkgconfig/createrepo_c.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libcreaterepo_c.so.1.1.3
/usr/lib64/libcreaterepo_c.so.1
/usr/lib64/libcreaterepo_c.so.1.1.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/createrepo_c/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/createrepo_c.8
/usr/share/man/man8/mergerepo_c.8
/usr/share/man/man8/modifyrepo_c.8
/usr/share/man/man8/sqliterepo_c.8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
